<?xml version="1.0" encoding="utf-8"?><Database Name="BBTapes" Class="BBTapesdbmlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\BBTapes.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BBTapesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Albums" Member="Albums">
    <Type Name="Album">
      <Column Name="Album_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Artist_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AlbumName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ReleaseDate" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Album_Image" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Album_CartItem" Member="CartItems" ThisKey="Album_ID" OtherKey="Album_ID" Type="CartItem" />
      <Association Name="Artist_Album" Member="Artist" ThisKey="Artist_ID" OtherKey="Artist_ID" Type="Artist" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Artist" Member="Artists">
    <Type Name="Artist">
      <Column Name="Artist_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Artist_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Artist_DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Artist_StageName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Artist_PlaceOfBirth" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Artist_Image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Artist_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Artist_Album" Member="Albums" ThisKey="Artist_ID" OtherKey="Artist_ID" Type="Album" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Contacts" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="User_CartItem" Member="CartItems" ThisKey="Id" OtherKey="Id" Type="CartItem" />
    </Type>
  </Table>
  <Table Name="dbo.CartItems" Member="CartItems">
    <Type Name="CartItem">
      <Column Name="Cart_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Album_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Album_CartItem" Member="Album" ThisKey="Album_ID" OtherKey="Album_ID" Type="Album" IsForeignKey="true" />
      <Association Name="User_CartItem" Member="User" ThisKey="Id" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>