//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtEaseWeb.AtEaseService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentClass", Namespace="http://schemas.datacontract.org/2004/07/AtEaseWCF")]
    [System.SerializableAttribute()]
    public partial class StudentClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string degreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isactiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stuNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contact {
            get {
                return this.contactField;
            }
            set {
                if ((object.ReferenceEquals(this.contactField, value) != true)) {
                    this.contactField = value;
                    this.RaisePropertyChanged("contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string degree {
            get {
                return this.degreeField;
            }
            set {
                if ((object.ReferenceEquals(this.degreeField, value) != true)) {
                    this.degreeField = value;
                    this.RaisePropertyChanged("degree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isactive {
            get {
                return this.isactiveField;
            }
            set {
                if ((this.isactiveField.Equals(value) != true)) {
                    this.isactiveField = value;
                    this.RaisePropertyChanged("isactive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stuNum {
            get {
                return this.stuNumField;
            }
            set {
                if ((object.ReferenceEquals(this.stuNumField, value) != true)) {
                    this.stuNumField = value;
                    this.RaisePropertyChanged("stuNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MerchantClass", Namespace="http://schemas.datacontract.org/2004/07/AtEaseWCF")]
    [System.SerializableAttribute()]
    public partial class MerchantClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isactiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int merchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int strikesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contact {
            get {
                return this.contactField;
            }
            set {
                if ((object.ReferenceEquals(this.contactField, value) != true)) {
                    this.contactField = value;
                    this.RaisePropertyChanged("contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isactive {
            get {
                return this.isactiveField;
            }
            set {
                if ((this.isactiveField.Equals(value) != true)) {
                    this.isactiveField = value;
                    this.RaisePropertyChanged("isactive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int merchID {
            get {
                return this.merchIDField;
            }
            set {
                if ((this.merchIDField.Equals(value) != true)) {
                    this.merchIDField = value;
                    this.RaisePropertyChanged("merchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int strikes {
            get {
                return this.strikesField;
            }
            set {
                if ((this.strikesField.Equals(value) != true)) {
                    this.strikesField = value;
                    this.RaisePropertyChanged("strikes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookClass", Namespace="http://schemas.datacontract.org/2004/07/AtEaseWCF")]
    [System.SerializableAttribute()]
    public partial class BookClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string authorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string editionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string author {
            get {
                return this.authorField;
            }
            set {
                if ((object.ReferenceEquals(this.authorField, value) != true)) {
                    this.authorField = value;
                    this.RaisePropertyChanged("author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string edition {
            get {
                return this.editionField;
            }
            set {
                if ((object.ReferenceEquals(this.editionField, value) != true)) {
                    this.editionField = value;
                    this.RaisePropertyChanged("edition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isbn {
            get {
                return this.isbnField;
            }
            set {
                if ((object.ReferenceEquals(this.isbnField, value) != true)) {
                    this.isbnField = value;
                    this.RaisePropertyChanged("isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductClass", Namespace="http://schemas.datacontract.org/2004/07/AtEaseWCF")]
    [System.SerializableAttribute()]
    public partial class ProductClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int merchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int prodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ratingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reviewsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isbn {
            get {
                return this.isbnField;
            }
            set {
                if ((object.ReferenceEquals(this.isbnField, value) != true)) {
                    this.isbnField = value;
                    this.RaisePropertyChanged("isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int merchID {
            get {
                return this.merchIDField;
            }
            set {
                if ((this.merchIDField.Equals(value) != true)) {
                    this.merchIDField = value;
                    this.RaisePropertyChanged("merchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int prodID {
            get {
                return this.prodIDField;
            }
            set {
                if ((this.prodIDField.Equals(value) != true)) {
                    this.prodIDField = value;
                    this.RaisePropertyChanged("prodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rating {
            get {
                return this.ratingField;
            }
            set {
                if ((this.ratingField.Equals(value) != true)) {
                    this.ratingField = value;
                    this.RaisePropertyChanged("rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reviews {
            get {
                return this.reviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.reviewsField, value) != true)) {
                    this.reviewsField = value;
                    this.RaisePropertyChanged("reviews");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuotationClass", Namespace="http://schemas.datacontract.org/2004/07/AtEaseWCF")]
    [System.SerializableAttribute()]
    public partial class QuotationClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> merchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quoteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string studentnumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isbn {
            get {
                return this.isbnField;
            }
            set {
                if ((object.ReferenceEquals(this.isbnField, value) != true)) {
                    this.isbnField = value;
                    this.RaisePropertyChanged("isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> merchID {
            get {
                return this.merchIDField;
            }
            set {
                if ((this.merchIDField.Equals(value) != true)) {
                    this.merchIDField = value;
                    this.RaisePropertyChanged("merchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quoteID {
            get {
                return this.quoteIDField;
            }
            set {
                if ((this.quoteIDField.Equals(value) != true)) {
                    this.quoteIDField = value;
                    this.RaisePropertyChanged("quoteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string studentnum {
            get {
                return this.studentnumField;
            }
            set {
                if ((object.ReferenceEquals(this.studentnumField, value) != true)) {
                    this.studentnumField = value;
                    this.RaisePropertyChanged("studentnum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeedbackClass", Namespace="http://schemas.datacontract.org/2004/07/AtEaseWCF")]
    [System.SerializableAttribute()]
    public partial class FeedbackClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int feedIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isRatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int merchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ratingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stuNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int feedID {
            get {
                return this.feedIDField;
            }
            set {
                if ((this.feedIDField.Equals(value) != true)) {
                    this.feedIDField = value;
                    this.RaisePropertyChanged("feedID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isRated {
            get {
                return this.isRatedField;
            }
            set {
                if ((this.isRatedField.Equals(value) != true)) {
                    this.isRatedField = value;
                    this.RaisePropertyChanged("isRated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int merchID {
            get {
                return this.merchIDField;
            }
            set {
                if ((this.merchIDField.Equals(value) != true)) {
                    this.merchIDField = value;
                    this.RaisePropertyChanged("merchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rating {
            get {
                return this.ratingField;
            }
            set {
                if ((this.ratingField.Equals(value) != true)) {
                    this.ratingField = value;
                    this.RaisePropertyChanged("rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string review {
            get {
                return this.reviewField;
            }
            set {
                if ((object.ReferenceEquals(this.reviewField, value) != true)) {
                    this.reviewField = value;
                    this.RaisePropertyChanged("review");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stuNum {
            get {
                return this.stuNumField;
            }
            set {
                if ((object.ReferenceEquals(this.stuNumField, value) != true)) {
                    this.stuNumField = value;
                    this.RaisePropertyChanged("stuNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AtEaseService.IAtEaseService")]
    public interface IAtEaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/RegisterStudent", ReplyAction="http://tempuri.org/IAtEaseService/RegisterStudentResponse")]
        bool RegisterStudent(AtEaseWeb.AtEaseService.StudentClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/RegisterStudent", ReplyAction="http://tempuri.org/IAtEaseService/RegisterStudentResponse")]
        System.Threading.Tasks.Task<bool> RegisterStudentAsync(AtEaseWeb.AtEaseService.StudentClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/IsStuRegistered", ReplyAction="http://tempuri.org/IAtEaseService/IsStuRegisteredResponse")]
        bool IsStuRegistered(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/IsStuRegistered", ReplyAction="http://tempuri.org/IAtEaseService/IsStuRegisteredResponse")]
        System.Threading.Tasks.Task<bool> IsStuRegisteredAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/RegisterMerchant", ReplyAction="http://tempuri.org/IAtEaseService/RegisterMerchantResponse")]
        bool RegisterMerchant(AtEaseWeb.AtEaseService.MerchantClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/RegisterMerchant", ReplyAction="http://tempuri.org/IAtEaseService/RegisterMerchantResponse")]
        System.Threading.Tasks.Task<bool> RegisterMerchantAsync(AtEaseWeb.AtEaseService.MerchantClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/IsMerchRegistered", ReplyAction="http://tempuri.org/IAtEaseService/IsMerchRegisteredResponse")]
        bool IsMerchRegistered(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/IsMerchRegistered", ReplyAction="http://tempuri.org/IAtEaseService/IsMerchRegisteredResponse")]
        System.Threading.Tasks.Task<bool> IsMerchRegisteredAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/StudentLogin", ReplyAction="http://tempuri.org/IAtEaseService/StudentLoginResponse")]
        int StudentLogin(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/StudentLogin", ReplyAction="http://tempuri.org/IAtEaseService/StudentLoginResponse")]
        System.Threading.Tasks.Task<int> StudentLoginAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/checkStudentActive", ReplyAction="http://tempuri.org/IAtEaseService/checkStudentActiveResponse")]
        bool checkStudentActive(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/checkStudentActive", ReplyAction="http://tempuri.org/IAtEaseService/checkStudentActiveResponse")]
        System.Threading.Tasks.Task<bool> checkStudentActiveAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetHomeBooks", ReplyAction="http://tempuri.org/IAtEaseService/GetHomeBooksResponse")]
        AtEaseWeb.AtEaseService.BookClass[] GetHomeBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetHomeBooks", ReplyAction="http://tempuri.org/IAtEaseService/GetHomeBooksResponse")]
        System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.BookClass[]> GetHomeBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/MerchantLogin", ReplyAction="http://tempuri.org/IAtEaseService/MerchantLoginResponse")]
        int MerchantLogin(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/MerchantLogin", ReplyAction="http://tempuri.org/IAtEaseService/MerchantLoginResponse")]
        System.Threading.Tasks.Task<int> MerchantLoginAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/checkMerchantActive", ReplyAction="http://tempuri.org/IAtEaseService/checkMerchantActiveResponse")]
        bool checkMerchantActive(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/checkMerchantActive", ReplyAction="http://tempuri.org/IAtEaseService/checkMerchantActiveResponse")]
        System.Threading.Tasks.Task<bool> checkMerchantActiveAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/ManagerLogin", ReplyAction="http://tempuri.org/IAtEaseService/ManagerLoginResponse")]
        int ManagerLogin(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/ManagerLogin", ReplyAction="http://tempuri.org/IAtEaseService/ManagerLoginResponse")]
        System.Threading.Tasks.Task<int> ManagerLoginAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/SearchBook", ReplyAction="http://tempuri.org/IAtEaseService/SearchBookResponse")]
        bool SearchBook(string SearchValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/SearchBook", ReplyAction="http://tempuri.org/IAtEaseService/SearchBookResponse")]
        System.Threading.Tasks.Task<bool> SearchBookAsync(string SearchValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetBook", ReplyAction="http://tempuri.org/IAtEaseService/GetBookResponse")]
        AtEaseWeb.AtEaseService.BookClass GetBook(string book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetBook", ReplyAction="http://tempuri.org/IAtEaseService/GetBookResponse")]
        System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.BookClass> GetBookAsync(string book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetProductMerchants", ReplyAction="http://tempuri.org/IAtEaseService/GetProductMerchantsResponse")]
        AtEaseWeb.AtEaseService.ProductClass[] GetProductMerchants(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetProductMerchants", ReplyAction="http://tempuri.org/IAtEaseService/GetProductMerchantsResponse")]
        System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.ProductClass[]> GetProductMerchantsAsync(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetMerchant", ReplyAction="http://tempuri.org/IAtEaseService/GetMerchantResponse")]
        AtEaseWeb.AtEaseService.MerchantClass GetMerchant(int merchid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetMerchant", ReplyAction="http://tempuri.org/IAtEaseService/GetMerchantResponse")]
        System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.MerchantClass> GetMerchantAsync(int merchid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetMerchProduct", ReplyAction="http://tempuri.org/IAtEaseService/GetMerchProductResponse")]
        AtEaseWeb.AtEaseService.ProductClass GetMerchProduct(string isbn, string merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetMerchProduct", ReplyAction="http://tempuri.org/IAtEaseService/GetMerchProductResponse")]
        System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.ProductClass> GetMerchProductAsync(string isbn, string merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/addtoQuote", ReplyAction="http://tempuri.org/IAtEaseService/addtoQuoteResponse")]
        bool addtoQuote(AtEaseWeb.AtEaseService.QuotationClass Q);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/addtoQuote", ReplyAction="http://tempuri.org/IAtEaseService/addtoQuoteResponse")]
        System.Threading.Tasks.Task<bool> addtoQuoteAsync(AtEaseWeb.AtEaseService.QuotationClass Q);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/getStuNumber", ReplyAction="http://tempuri.org/IAtEaseService/getStuNumberResponse")]
        string getStuNumber(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/getStuNumber", ReplyAction="http://tempuri.org/IAtEaseService/getStuNumberResponse")]
        System.Threading.Tasks.Task<string> getStuNumberAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/getQuoteInfo", ReplyAction="http://tempuri.org/IAtEaseService/getQuoteInfoResponse")]
        AtEaseWeb.AtEaseService.QuotationClass[] getQuoteInfo(string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/getQuoteInfo", ReplyAction="http://tempuri.org/IAtEaseService/getQuoteInfoResponse")]
        System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.QuotationClass[]> getQuoteInfoAsync(string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/removeFromQuote", ReplyAction="http://tempuri.org/IAtEaseService/removeFromQuoteResponse")]
        bool removeFromQuote(string isbn, int merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/removeFromQuote", ReplyAction="http://tempuri.org/IAtEaseService/removeFromQuoteResponse")]
        System.Threading.Tasks.Task<bool> removeFromQuoteAsync(string isbn, int merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetMerchRating", ReplyAction="http://tempuri.org/IAtEaseService/GetMerchRatingResponse")]
        int GetMerchRating(int MerchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetMerchRating", ReplyAction="http://tempuri.org/IAtEaseService/GetMerchRatingResponse")]
        System.Threading.Tasks.Task<int> GetMerchRatingAsync(int MerchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetMerchID", ReplyAction="http://tempuri.org/IAtEaseService/GetMerchIDResponse")]
        int GetMerchID(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetMerchID", ReplyAction="http://tempuri.org/IAtEaseService/GetMerchIDResponse")]
        System.Threading.Tasks.Task<int> GetMerchIDAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/AllMerchProducts", ReplyAction="http://tempuri.org/IAtEaseService/AllMerchProductsResponse")]
        AtEaseWeb.AtEaseService.ProductClass[] AllMerchProducts(int MerchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/AllMerchProducts", ReplyAction="http://tempuri.org/IAtEaseService/AllMerchProductsResponse")]
        System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.ProductClass[]> AllMerchProductsAsync(int MerchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/EditMerchant", ReplyAction="http://tempuri.org/IAtEaseService/EditMerchantResponse")]
        bool EditMerchant(AtEaseWeb.AtEaseService.MerchantClass m, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/EditMerchant", ReplyAction="http://tempuri.org/IAtEaseService/EditMerchantResponse")]
        System.Threading.Tasks.Task<bool> EditMerchantAsync(AtEaseWeb.AtEaseService.MerchantClass m, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/AddMerchProduct", ReplyAction="http://tempuri.org/IAtEaseService/AddMerchProductResponse")]
        bool AddMerchProduct(AtEaseWeb.AtEaseService.ProductClass mbc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/AddMerchProduct", ReplyAction="http://tempuri.org/IAtEaseService/AddMerchProductResponse")]
        System.Threading.Tasks.Task<bool> AddMerchProductAsync(AtEaseWeb.AtEaseService.ProductClass mbc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/IsNewMerchBook", ReplyAction="http://tempuri.org/IAtEaseService/IsNewMerchBookResponse")]
        bool IsNewMerchBook(string isbn, int merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/IsNewMerchBook", ReplyAction="http://tempuri.org/IAtEaseService/IsNewMerchBookResponse")]
        System.Threading.Tasks.Task<bool> IsNewMerchBookAsync(string isbn, int merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetAllMerchants", ReplyAction="http://tempuri.org/IAtEaseService/GetAllMerchantsResponse")]
        AtEaseWeb.AtEaseService.MerchantClass[] GetAllMerchants();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetAllMerchants", ReplyAction="http://tempuri.org/IAtEaseService/GetAllMerchantsResponse")]
        System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.MerchantClass[]> GetAllMerchantsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/removeMerchProduct", ReplyAction="http://tempuri.org/IAtEaseService/removeMerchProductResponse")]
        bool removeMerchProduct(string isbn, int merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/removeMerchProduct", ReplyAction="http://tempuri.org/IAtEaseService/removeMerchProductResponse")]
        System.Threading.Tasks.Task<bool> removeMerchProductAsync(string isbn, int merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/SetMerchPrice", ReplyAction="http://tempuri.org/IAtEaseService/SetMerchPriceResponse")]
        bool SetMerchPrice(int price, string name, int merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/SetMerchPrice", ReplyAction="http://tempuri.org/IAtEaseService/SetMerchPriceResponse")]
        System.Threading.Tasks.Task<bool> SetMerchPriceAsync(int price, string name, int merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/getISBN", ReplyAction="http://tempuri.org/IAtEaseService/getISBNResponse")]
        string getISBN(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/getISBN", ReplyAction="http://tempuri.org/IAtEaseService/getISBNResponse")]
        System.Threading.Tasks.Task<string> getISBNAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetMerchReviews", ReplyAction="http://tempuri.org/IAtEaseService/GetMerchReviewsResponse")]
        string[] GetMerchReviews(int merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetMerchReviews", ReplyAction="http://tempuri.org/IAtEaseService/GetMerchReviewsResponse")]
        System.Threading.Tasks.Task<string[]> GetMerchReviewsAsync(int merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/setRating", ReplyAction="http://tempuri.org/IAtEaseService/setRatingResponse")]
        bool setRating(int rating, string stuNum, int merch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/setRating", ReplyAction="http://tempuri.org/IAtEaseService/setRatingResponse")]
        System.Threading.Tasks.Task<bool> setRatingAsync(int rating, string stuNum, int merch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/setReview", ReplyAction="http://tempuri.org/IAtEaseService/setReviewResponse")]
        bool setReview(string rev, string stuNum, int merch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/setReview", ReplyAction="http://tempuri.org/IAtEaseService/setReviewResponse")]
        System.Threading.Tasks.Task<bool> setReviewAsync(string rev, string stuNum, int merch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/setFeedback", ReplyAction="http://tempuri.org/IAtEaseService/setFeedbackResponse")]
        bool setFeedback(AtEaseWeb.AtEaseService.FeedbackClass fb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/setFeedback", ReplyAction="http://tempuri.org/IAtEaseService/setFeedbackResponse")]
        System.Threading.Tasks.Task<bool> setFeedbackAsync(AtEaseWeb.AtEaseService.FeedbackClass fb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/getAllFeedback", ReplyAction="http://tempuri.org/IAtEaseService/getAllFeedbackResponse")]
        AtEaseWeb.AtEaseService.FeedbackClass[] getAllFeedback(string stuNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/getAllFeedback", ReplyAction="http://tempuri.org/IAtEaseService/getAllFeedbackResponse")]
        System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.FeedbackClass[]> getAllFeedbackAsync(string stuNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/setIsRated", ReplyAction="http://tempuri.org/IAtEaseService/setIsRatedResponse")]
        bool setIsRated(string stuNummber, int merchId, int val);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/setIsRated", ReplyAction="http://tempuri.org/IAtEaseService/setIsRatedResponse")]
        System.Threading.Tasks.Task<bool> setIsRatedAsync(string stuNummber, int merchId, int val);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetIsRated", ReplyAction="http://tempuri.org/IAtEaseService/GetIsRatedResponse")]
        int GetIsRated(int merchID, string stuNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/GetIsRated", ReplyAction="http://tempuri.org/IAtEaseService/GetIsRatedResponse")]
        System.Threading.Tasks.Task<int> GetIsRatedAsync(int merchID, string stuNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/reportMerchant", ReplyAction="http://tempuri.org/IAtEaseService/reportMerchantResponse")]
        bool reportMerchant(int merID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/reportMerchant", ReplyAction="http://tempuri.org/IAtEaseService/reportMerchantResponse")]
        System.Threading.Tasks.Task<bool> reportMerchantAsync(int merID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/removeMerchant", ReplyAction="http://tempuri.org/IAtEaseService/removeMerchantResponse")]
        bool removeMerchant(int merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/removeMerchant", ReplyAction="http://tempuri.org/IAtEaseService/removeMerchantResponse")]
        System.Threading.Tasks.Task<bool> removeMerchantAsync(int merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/removeOwnerProducts", ReplyAction="http://tempuri.org/IAtEaseService/removeOwnerProductsResponse")]
        bool removeOwnerProducts(int merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/removeOwnerProducts", ReplyAction="http://tempuri.org/IAtEaseService/removeOwnerProductsResponse")]
        System.Threading.Tasks.Task<bool> removeOwnerProductsAsync(int merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/removefromFeed", ReplyAction="http://tempuri.org/IAtEaseService/removefromFeedResponse")]
        bool removefromFeed(int merchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtEaseService/removefromFeed", ReplyAction="http://tempuri.org/IAtEaseService/removefromFeedResponse")]
        System.Threading.Tasks.Task<bool> removefromFeedAsync(int merchID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAtEaseServiceChannel : AtEaseWeb.AtEaseService.IAtEaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AtEaseServiceClient : System.ServiceModel.ClientBase<AtEaseWeb.AtEaseService.IAtEaseService>, AtEaseWeb.AtEaseService.IAtEaseService {
        
        public AtEaseServiceClient() {
        }
        
        public AtEaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AtEaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AtEaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AtEaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterStudent(AtEaseWeb.AtEaseService.StudentClass s) {
            return base.Channel.RegisterStudent(s);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterStudentAsync(AtEaseWeb.AtEaseService.StudentClass s) {
            return base.Channel.RegisterStudentAsync(s);
        }
        
        public bool IsStuRegistered(string Email) {
            return base.Channel.IsStuRegistered(Email);
        }
        
        public System.Threading.Tasks.Task<bool> IsStuRegisteredAsync(string Email) {
            return base.Channel.IsStuRegisteredAsync(Email);
        }
        
        public bool RegisterMerchant(AtEaseWeb.AtEaseService.MerchantClass s) {
            return base.Channel.RegisterMerchant(s);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterMerchantAsync(AtEaseWeb.AtEaseService.MerchantClass s) {
            return base.Channel.RegisterMerchantAsync(s);
        }
        
        public bool IsMerchRegistered(string Email) {
            return base.Channel.IsMerchRegistered(Email);
        }
        
        public System.Threading.Tasks.Task<bool> IsMerchRegisteredAsync(string Email) {
            return base.Channel.IsMerchRegisteredAsync(Email);
        }
        
        public int StudentLogin(string Email, string Password) {
            return base.Channel.StudentLogin(Email, Password);
        }
        
        public System.Threading.Tasks.Task<int> StudentLoginAsync(string Email, string Password) {
            return base.Channel.StudentLoginAsync(Email, Password);
        }
        
        public bool checkStudentActive(string email) {
            return base.Channel.checkStudentActive(email);
        }
        
        public System.Threading.Tasks.Task<bool> checkStudentActiveAsync(string email) {
            return base.Channel.checkStudentActiveAsync(email);
        }
        
        public AtEaseWeb.AtEaseService.BookClass[] GetHomeBooks() {
            return base.Channel.GetHomeBooks();
        }
        
        public System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.BookClass[]> GetHomeBooksAsync() {
            return base.Channel.GetHomeBooksAsync();
        }
        
        public int MerchantLogin(string Email, string Password) {
            return base.Channel.MerchantLogin(Email, Password);
        }
        
        public System.Threading.Tasks.Task<int> MerchantLoginAsync(string Email, string Password) {
            return base.Channel.MerchantLoginAsync(Email, Password);
        }
        
        public bool checkMerchantActive(string email) {
            return base.Channel.checkMerchantActive(email);
        }
        
        public System.Threading.Tasks.Task<bool> checkMerchantActiveAsync(string email) {
            return base.Channel.checkMerchantActiveAsync(email);
        }
        
        public int ManagerLogin(string Email, string Password) {
            return base.Channel.ManagerLogin(Email, Password);
        }
        
        public System.Threading.Tasks.Task<int> ManagerLoginAsync(string Email, string Password) {
            return base.Channel.ManagerLoginAsync(Email, Password);
        }
        
        public bool SearchBook(string SearchValue) {
            return base.Channel.SearchBook(SearchValue);
        }
        
        public System.Threading.Tasks.Task<bool> SearchBookAsync(string SearchValue) {
            return base.Channel.SearchBookAsync(SearchValue);
        }
        
        public AtEaseWeb.AtEaseService.BookClass GetBook(string book) {
            return base.Channel.GetBook(book);
        }
        
        public System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.BookClass> GetBookAsync(string book) {
            return base.Channel.GetBookAsync(book);
        }
        
        public AtEaseWeb.AtEaseService.ProductClass[] GetProductMerchants(string isbn) {
            return base.Channel.GetProductMerchants(isbn);
        }
        
        public System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.ProductClass[]> GetProductMerchantsAsync(string isbn) {
            return base.Channel.GetProductMerchantsAsync(isbn);
        }
        
        public AtEaseWeb.AtEaseService.MerchantClass GetMerchant(int merchid) {
            return base.Channel.GetMerchant(merchid);
        }
        
        public System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.MerchantClass> GetMerchantAsync(int merchid) {
            return base.Channel.GetMerchantAsync(merchid);
        }
        
        public AtEaseWeb.AtEaseService.ProductClass GetMerchProduct(string isbn, string merchID) {
            return base.Channel.GetMerchProduct(isbn, merchID);
        }
        
        public System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.ProductClass> GetMerchProductAsync(string isbn, string merchID) {
            return base.Channel.GetMerchProductAsync(isbn, merchID);
        }
        
        public bool addtoQuote(AtEaseWeb.AtEaseService.QuotationClass Q) {
            return base.Channel.addtoQuote(Q);
        }
        
        public System.Threading.Tasks.Task<bool> addtoQuoteAsync(AtEaseWeb.AtEaseService.QuotationClass Q) {
            return base.Channel.addtoQuoteAsync(Q);
        }
        
        public string getStuNumber(string email) {
            return base.Channel.getStuNumber(email);
        }
        
        public System.Threading.Tasks.Task<string> getStuNumberAsync(string email) {
            return base.Channel.getStuNumberAsync(email);
        }
        
        public AtEaseWeb.AtEaseService.QuotationClass[] getQuoteInfo(string number) {
            return base.Channel.getQuoteInfo(number);
        }
        
        public System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.QuotationClass[]> getQuoteInfoAsync(string number) {
            return base.Channel.getQuoteInfoAsync(number);
        }
        
        public bool removeFromQuote(string isbn, int merchID) {
            return base.Channel.removeFromQuote(isbn, merchID);
        }
        
        public System.Threading.Tasks.Task<bool> removeFromQuoteAsync(string isbn, int merchID) {
            return base.Channel.removeFromQuoteAsync(isbn, merchID);
        }
        
        public int GetMerchRating(int MerchID) {
            return base.Channel.GetMerchRating(MerchID);
        }
        
        public System.Threading.Tasks.Task<int> GetMerchRatingAsync(int MerchID) {
            return base.Channel.GetMerchRatingAsync(MerchID);
        }
        
        public int GetMerchID(string Email) {
            return base.Channel.GetMerchID(Email);
        }
        
        public System.Threading.Tasks.Task<int> GetMerchIDAsync(string Email) {
            return base.Channel.GetMerchIDAsync(Email);
        }
        
        public AtEaseWeb.AtEaseService.ProductClass[] AllMerchProducts(int MerchID) {
            return base.Channel.AllMerchProducts(MerchID);
        }
        
        public System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.ProductClass[]> AllMerchProductsAsync(int MerchID) {
            return base.Channel.AllMerchProductsAsync(MerchID);
        }
        
        public bool EditMerchant(AtEaseWeb.AtEaseService.MerchantClass m, string email) {
            return base.Channel.EditMerchant(m, email);
        }
        
        public System.Threading.Tasks.Task<bool> EditMerchantAsync(AtEaseWeb.AtEaseService.MerchantClass m, string email) {
            return base.Channel.EditMerchantAsync(m, email);
        }
        
        public bool AddMerchProduct(AtEaseWeb.AtEaseService.ProductClass mbc) {
            return base.Channel.AddMerchProduct(mbc);
        }
        
        public System.Threading.Tasks.Task<bool> AddMerchProductAsync(AtEaseWeb.AtEaseService.ProductClass mbc) {
            return base.Channel.AddMerchProductAsync(mbc);
        }
        
        public bool IsNewMerchBook(string isbn, int merchID) {
            return base.Channel.IsNewMerchBook(isbn, merchID);
        }
        
        public System.Threading.Tasks.Task<bool> IsNewMerchBookAsync(string isbn, int merchID) {
            return base.Channel.IsNewMerchBookAsync(isbn, merchID);
        }
        
        public AtEaseWeb.AtEaseService.MerchantClass[] GetAllMerchants() {
            return base.Channel.GetAllMerchants();
        }
        
        public System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.MerchantClass[]> GetAllMerchantsAsync() {
            return base.Channel.GetAllMerchantsAsync();
        }
        
        public bool removeMerchProduct(string isbn, int merchID) {
            return base.Channel.removeMerchProduct(isbn, merchID);
        }
        
        public System.Threading.Tasks.Task<bool> removeMerchProductAsync(string isbn, int merchID) {
            return base.Channel.removeMerchProductAsync(isbn, merchID);
        }
        
        public bool SetMerchPrice(int price, string name, int merchID) {
            return base.Channel.SetMerchPrice(price, name, merchID);
        }
        
        public System.Threading.Tasks.Task<bool> SetMerchPriceAsync(int price, string name, int merchID) {
            return base.Channel.SetMerchPriceAsync(price, name, merchID);
        }
        
        public string getISBN(string name) {
            return base.Channel.getISBN(name);
        }
        
        public System.Threading.Tasks.Task<string> getISBNAsync(string name) {
            return base.Channel.getISBNAsync(name);
        }
        
        public string[] GetMerchReviews(int merchID) {
            return base.Channel.GetMerchReviews(merchID);
        }
        
        public System.Threading.Tasks.Task<string[]> GetMerchReviewsAsync(int merchID) {
            return base.Channel.GetMerchReviewsAsync(merchID);
        }
        
        public bool setRating(int rating, string stuNum, int merch) {
            return base.Channel.setRating(rating, stuNum, merch);
        }
        
        public System.Threading.Tasks.Task<bool> setRatingAsync(int rating, string stuNum, int merch) {
            return base.Channel.setRatingAsync(rating, stuNum, merch);
        }
        
        public bool setReview(string rev, string stuNum, int merch) {
            return base.Channel.setReview(rev, stuNum, merch);
        }
        
        public System.Threading.Tasks.Task<bool> setReviewAsync(string rev, string stuNum, int merch) {
            return base.Channel.setReviewAsync(rev, stuNum, merch);
        }
        
        public bool setFeedback(AtEaseWeb.AtEaseService.FeedbackClass fb) {
            return base.Channel.setFeedback(fb);
        }
        
        public System.Threading.Tasks.Task<bool> setFeedbackAsync(AtEaseWeb.AtEaseService.FeedbackClass fb) {
            return base.Channel.setFeedbackAsync(fb);
        }
        
        public AtEaseWeb.AtEaseService.FeedbackClass[] getAllFeedback(string stuNum) {
            return base.Channel.getAllFeedback(stuNum);
        }
        
        public System.Threading.Tasks.Task<AtEaseWeb.AtEaseService.FeedbackClass[]> getAllFeedbackAsync(string stuNum) {
            return base.Channel.getAllFeedbackAsync(stuNum);
        }
        
        public bool setIsRated(string stuNummber, int merchId, int val) {
            return base.Channel.setIsRated(stuNummber, merchId, val);
        }
        
        public System.Threading.Tasks.Task<bool> setIsRatedAsync(string stuNummber, int merchId, int val) {
            return base.Channel.setIsRatedAsync(stuNummber, merchId, val);
        }
        
        public int GetIsRated(int merchID, string stuNum) {
            return base.Channel.GetIsRated(merchID, stuNum);
        }
        
        public System.Threading.Tasks.Task<int> GetIsRatedAsync(int merchID, string stuNum) {
            return base.Channel.GetIsRatedAsync(merchID, stuNum);
        }
        
        public bool reportMerchant(int merID) {
            return base.Channel.reportMerchant(merID);
        }
        
        public System.Threading.Tasks.Task<bool> reportMerchantAsync(int merID) {
            return base.Channel.reportMerchantAsync(merID);
        }
        
        public bool removeMerchant(int merchID) {
            return base.Channel.removeMerchant(merchID);
        }
        
        public System.Threading.Tasks.Task<bool> removeMerchantAsync(int merchID) {
            return base.Channel.removeMerchantAsync(merchID);
        }
        
        public bool removeOwnerProducts(int merchID) {
            return base.Channel.removeOwnerProducts(merchID);
        }
        
        public System.Threading.Tasks.Task<bool> removeOwnerProductsAsync(int merchID) {
            return base.Channel.removeOwnerProductsAsync(merchID);
        }
        
        public bool removefromFeed(int merchID) {
            return base.Channel.removefromFeed(merchID);
        }
        
        public System.Threading.Tasks.Task<bool> removefromFeedAsync(int merchID) {
            return base.Channel.removefromFeedAsync(merchID);
        }
    }
}
